FROM node:latest
WORKDIR /app
COPY . /app
RUN yarn

# Указание аргументов
ARG MNEMONIC
ARG SUPABASE_PUBLIC_KEY
ARG SUPABASE_URL
ARG TG_BOT_TOKEN
ARG TG_GROUP_ID
ARG TONAPI_TOKEN

ENV MAIN_MNEMONIC=$MNEMONIC
ENV PUBLIC_KEY=$SUPABASE_PUBLIC_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV TG_BOT_TOKEN=$TG_BOT_TOKEN
ENV TG_GROUP_ID=$TG_GROUP_ID
ENV TONAPI_TOKEN=$TONAPI_TOKEN
CMD ["yarn","start"]
