export const dedustAssets = [
    {
        type: 'native',
        name: 'Toncoin',
        symbol: 'TON',
        image: 'https://assets.dedust.io/images/ton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBlqsm144Dq6SjbPI4jjZvA1hqTIP3CvHovbIfW_t-SCALE',
        name: 'Scaleton',
        symbol: 'SCALE',
        image: 'https://assets.dedust.io/images/scale.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs',
        name: 'Tether USD',
        symbol: 'USDT',
        image: 'https://assets.dedust.io/images/usdt.webp',
        decimals: 6,
        source: {
            chain: 'eip155:1',
            address: '',
            bridge: '',
            symbol: 'USDT',
            name: 'Tether USD',
        },
    },
    {
        type: 'jetton',
        address: 'EQBynBO23ywHy_CgarY9NK9FTz0yDsG82PtcbSTQgGoXwiuA',
        name: 'TON Bridge USDT',
        symbol: 'jUSDT',
        image: 'https://assets.dedust.io/images/usdt-old.webp',
        decimals: 6,
        source: {
            chain: 'eip155:1',
            address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            bridge: 'ton-bridge',
            symbol: 'USDT',
            name: 'Tether USD',
        },
    },
    {
        type: 'jetton',
        address: 'EQAQXlWJvGbbFfE8F3oS8s87lIgdovS455IsWFaRdmJetTon',
        name: 'JetTon',
        symbol: 'JETTON',
        image: 'https://assets.dedust.io/images/jetton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB-MPwrd1G6WKNkLz_VnV6WqBDd142KMQv-g1O-8QUA3728',
        name: 'TON Bridge USDC',
        symbol: 'jUSDC',
        image: 'https://assets.dedust.io/images/usdc.webp',
        decimals: 6,
        source: {
            chain: 'eip155:1',
            address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
            bridge: 'ton-bridge',
            symbol: 'USDC',
            name: 'USD Coin',
        },
    },
    {
        type: 'jetton',
        address: 'EQDcBkGHmC4pTf34x3Gm05XvepO5w60DNxZ-XT4I6-UGG5L5',
        name: 'TON Bridge WBTC',
        symbol: 'jWBTC',
        image: 'https://assets.dedust.io/images/wbtc.webp',
        decimals: 8,
        source: {
            chain: 'eip155:1',
            address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
            bridge: 'ton-bridge',
            symbol: 'WBTC',
            name: 'Wrapped BTC',
        },
    },
    {
        type: 'jetton',
        address: 'EQDo_ZJyQ_YqBzBwbVpMmhbhIddKtRP99HugZJ14aFscxi7B',
        name: 'TON Bridge DAI',
        symbol: 'jDAI',
        image: 'https://assets.dedust.io/images/dai.webp',
        decimals: 18,
        source: {
            chain: 'eip155:1',
            address: '0x6b175474e89094c44da98b954eedeac495271d0f',
            bridge: 'ton-bridge',
            symbol: 'DAI',
            name: 'Dai Stablecoin',
        },
    },
    {
        type: 'jetton',
        address: 'EQC_1YoM8RBixN95lz7odcF3Vrkc_N8Ne7gQi7Abtlet_Efi',
        name: 'Orbit Bridge USDT',
        symbol: 'oUSDT',
        image: 'https://assets.dedust.io/images/orbit-usdt.webp',
        decimals: 6,
        source: {
            chain: 'eip155:1',
            address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
            bridge: 'orbit-bridge',
            symbol: 'USDT',
            name: 'Tether USD',
        },
    },
    {
        type: 'jetton',
        address: 'EQC61IQRl0_la95t27xhIpjxZt32vl1QQVF2UgTNuvD18W-4',
        name: 'Orbit Bridge USDC',
        symbol: 'oUSDC',
        image: 'https://assets.dedust.io/images/orbit-usdc.webp',
        decimals: 6,
        source: {
            chain: 'eip155:1',
            address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
            bridge: 'orbit-bridge',
            symbol: 'USDC',
            name: 'USD Coin',
        },
    },
    {
        type: 'jetton',
        address: 'EQANasbzD5wdVx0qikebkchrH64zNgsB38oC9PVu7rG16qNB',
        name: 'Orbit Bridge WBTC',
        symbol: 'oWBTC',
        image: 'https://assets.dedust.io/images/orbit-wbtc.webp',
        decimals: 8,
        source: {
            chain: 'eip155:1',
            address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
            bridge: 'orbit-bridge',
            symbol: 'BTC',
            name: 'Wrapped BTC',
        },
    },
    {
        type: 'jetton',
        address: 'EQAAXwH0cajPsMF-nNC5kz-SaLaeaDr4M7Q1foVwP_vOW1tR',
        name: 'Orbit Bridge DAI',
        symbol: 'oDAI',
        image: 'https://assets.dedust.io/images/orbit-dai.webp',
        decimals: 18,
        source: {
            chain: 'eip155:1',
            address: '0x6b175474e89094c44da98b954eedeac495271d0f',
            bridge: 'orbit-bridge',
            symbol: 'DAI',
            name: 'Dai Stablecoin',
        },
    },
    {
        type: 'jetton',
        address: 'EQDNhy-nxYFgUqzfUzImBEP67JqsyMIcyk2S5_RwNNEYku0k',
        name: 'Staked TON by bemo',
        symbol: 'stTON',
        image: 'https://assets.dedust.io/images/stton-bemo.webp',
        decimals: 9,
        source: {
            chain: 'eip155:1',
            address: '',
            bridge: 'none',
            symbol: 'stTON',
            name: 'Staked TON by bemo',
        },
    },
    {
        type: 'jetton',
        address: 'EQB0SoxuGDx5qjVt0P_bPICFeWdFLBmVopHhjgfs0q-wsTON',
        name: 'Ton Whales liquid staking token',
        symbol: 'wsTON',
        image: 'https://assets.dedust.io/images/wston-whales.webp',
        decimals: 9,
        source: {
            chain: 'eip155:1',
            address: '',
            bridge: 'none',
            symbol: 'wsTON',
            name: 'Ton Whales liquid staking token',
        },
    },
    {
        type: 'jetton',
        address: 'EQCcLAW537KnRg_aSPrnQJoyYjOZkzqYp6FVmRUvN1crSazV',
        name: 'Ambra',
        symbol: 'AMBR',
        image: 'https://assets.dedust.io/images/ambr.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCBdxpECfEPH2wUxi1a6QiOkSf-5qDjUWqLCUuKtD-GLINT',
        name: 'Glint Coin',
        symbol: 'GLINT',
        image: 'https://assets.dedust.io/images/glint.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCJbp0kBpPwPoBG-U5C-cWfP_jnksvotGfArPF50Q9Qiv9h',
        name: 'Ton Raffles Token',
        symbol: 'RAFF',
        image: 'https://assets.dedust.io/images/raff.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD0vdSA_NedR9uvbgN9EikRX-suesDxGeFg69XQMavfLqIw',
        name: 'Bolt',
        symbol: 'BOLT',
        image: 'https://assets.dedust.io/images/bolt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBjEw-SOe8yV2kIbGVZGrsPpLTaaoAOE87CGXI2ca4XdzXA',
        name: 'Margaritis',
        symbol: 'MARGA',
        image: 'https://assets.dedust.io/images/marga.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCbKMTmEAdSnzsK85LOpaDkDH3HjujEbTePMSeirvEaNq-U',
        name: 'Magic Crystal',
        symbol: 'MC',
        image: 'https://assets.dedust.io/images/mc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC-tdRjjoYMz3MXKW4pj95bNZgvRyWwZ23Jix3ph7guvHxJ',
        name: 'KINGYTON',
        symbol: 'KINGY',
        image: 'https://assets.dedust.io/images/kingy.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB-ajMyi5-WKIgOHnbOGApfckUGbl6tDk3Qt8PKmb-xLAvp',
        name: 'TonexCoin',
        symbol: 'TNX',
        image: 'https://assets.dedust.io/images/tnx.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCQZpelevHNsbw5IUtwSa4Cs8kqWww0KsYeDri9kwS18eCz',
        name: 'DYOR Coin',
        symbol: 'DYOR',
        image: 'https://assets.dedust.io/images/dyor.webp',
        decimals: 15,
    },
    {
        type: 'jetton',
        address: 'EQBJOJ2eL_CUFT_0r9meoqjKUwRttC_-NUJyvWQxszVWe1WY',
        name: 'Petcoin',
        symbol: 'PET',
        image: 'https://assets.dedust.io/images/pet.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDNDv54v_TEU5t26rFykylsdPQsv5nsSZaH_v7JSJPtMitv',
        name: 'Tonnel Network Token',
        symbol: 'TONNEL',
        image: 'https://assets.dedust.io/images/tonnel.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD_KpO2-iFeHPT4dF0ur9E0iAFts2fwhpR2KjwAmYKpccvH',
        name: 'ЖЮ',
        symbol: 'LIFEYT',
        image: 'https://assets.dedust.io/images/lifeyt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAM2KWDp9lN0YvxvfSbI0ryjBXwM70rakpNIHbuETatRWA1',
        name: 'ARBUZ',
        symbol: 'ARBUZ',
        image: 'https://assets.dedust.io/images/arbuz.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCu9qafFYH1tbvBCsVg6QQwPbLinzQ27HKkr0Tb4WSobXI-',
        name: 'MONK',
        symbol: 'MONK',
        image: 'https://assets.dedust.io/images/monk.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCvaf0JMrv6BOvPpAgee08uQM_uRpUd__fhA7Nm8twzvbE_',
        name: 'TonUP',
        symbol: 'UP',
        image: 'https://assets.dedust.io/images/up.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBk0iOnG6u4yVzf4HfZf7EGuetWiKbyR5GApBgblmeG-jPL',
        name: 'RED X',
        symbol: 'REDX',
        image: 'https://assets.dedust.io/images/redx.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD0nt2W1YwJFdMQ-GIx4jguNbvbjS-aM32jOW7hTQs58lds',
        name: 'Grabscape governance token',
        symbol: 'GGT',
        image: 'https://assets.dedust.io/images/ggt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCW5g1evnQN2OZZEVe-23aSvEsgPauWZlF27ZIz5REhnWRy',
        name: 'DEFI HUNTERS DAO',
        symbol: 'DDAO',
        image: 'https://assets.dedust.io/images/ddao.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC-A0ZHiAliPJ6LYQQZ6x2WRJC0aHEmJ_OMG6pidb5ASpIY',
        name: 'EXTON COIN',
        symbol: 'EXC',
        image: 'https://assets.dedust.io/images/exc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBCFwW8uFUh-amdRmNY9NyeDEaeDYXd9ggJGsicpqVcHq7B',
        name: 'DHD Coin',
        symbol: 'DHD',
        image: 'https://assets.dedust.io/images/dhd.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBj7uoIVsngmS-ayOz1nHENjZkjTt5mXB4uGa83hmcqq2wA',
        name: 'Grabscape game token',
        symbol: 'GRBS',
        image: 'https://assets.dedust.io/images/grbs.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBiJ8dSbp3_YAb_KuC64zCrFqQTsFbUee5tbzr5el_HEDGE',
        name: 'HEDGE coin',
        symbol: 'HEDGE',
        image: 'https://assets.dedust.io/images/hedge.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAvvEdq4x5K6owjsMI4X6AxKkTBXVKIVkiSHDLt6i2LFnnQ',
        name: 'Bear Country Token',
        symbol: 'JBCT',
        image: 'https://assets.dedust.io/images/jbct.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBtFN8h8dStTvI58tESc_S70ehkBLSuzQqCg5BLIQyKMBC1',
        name: 'VOMER',
        symbol: 'VMR',
        image: 'https://assets.dedust.io/images/vmr.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBl3gg6AAdjgjO2ZoNU5Q5EzUIl8XMNZrix8Z5dJmkHUfxI',
        name: 'Lavandos',
        symbol: 'LAVE',
        image: 'https://assets.dedust.io/images/lave.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCPmOnkTe8qP_ZtCf3Rys04ukRTiQc_xVS-lGQ6BH3JZWmC',
        name: 'Tenere',
        symbol: 'TNR',
        image: 'https://assets.dedust.io/images/tnr.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAj18Ki4sG47AXb14No35FnrMNBxC2uHcuIejJDyrd6VXpQ',
        name: 'PAPA CARLO',
        symbol: 'PC',
        image: 'https://assets.dedust.io/images/pc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBtUKPbhABPYtltiKWA547s4ZhJ5wZHvVV1eyfV7sEyGs2J',
        name: 'Wallet Exchanger',
        symbol: 'WEX',
        image: 'https://assets.dedust.io/images/wex.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBzyesZ3p1WGNrggNSJi6JFK3vr0GhqJp4gxker9oujjcuv',
        name: 'TonTake',
        symbol: 'TAKE',
        image: 'https://assets.dedust.io/images/take.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCfJ4Su11h0_MB2XRvIjm8gw0y2AB4RZEfOoPOweyVIzvda',
        name: 'Milyman',
        symbol: 'MILY',
        image: 'https://assets.dedust.io/images/mily.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDqQscohYilSqWEyeLyCReOQKOh7KhRX_CPlD-Qdx02tUbG',
        name: 'Vincere',
        symbol: 'VC',
        image: 'https://assets.dedust.io/images/vincere.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQACGPrFHWCy9QmeFXPqvZflyoeBb5grVQxAaucF0hNd1sEs',
        name: 'Stalin',
        symbol: 'IVS',
        image: 'https://assets.dedust.io/images/ivs.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAYBDuLdLrjDKR1SUZ60ZuLuSzHDIoE26zZExuB_bjiG0Zr',
        name: 'TON Click',
        symbol: 'CLICK',
        image: 'https://assets.dedust.io/images/click.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDCAjHxgyScUPS-Am_2nAH7C5XWM4fc2X9dVyWpFgHXG2rT',
        name: 'EggsWisdom',
        symbol: 'EGG',
        image: 'https://assets.dedust.io/images/egg.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAS2elYb6_hqWyOl7gpuYTzf1sqmjLJQ0lQ4X_4d_MvtMWR',
        name: 'Love You',
        symbol: 'LOVE',
        image: 'https://assets.dedust.io/images/love.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD26zcd6Cqpz7WyLKVH8x_cD6D7tBrom6hKcycv8L8hV0GP',
        name: 'DeFinder Capital',
        symbol: 'DFC',
        image: 'https://assets.dedust.io/images/dfc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAhRC_oZ4B9VgMltfNkENSdLktlMADPE73zIiIcL6es2o7-',
        name: 'TON Drift',
        symbol: 'DRIFT',
        image: 'https://assets.dedust.io/images/drift.webp',
        decimals: 10,
    },
    {
        type: 'jetton',
        address: 'EQCyDhcASwIm8-eVVTzMEESYAeQ7ettasfuGXUG1tkDwVJbc',
        name: 'Lucky TON',
        symbol: 'LKY',
        image: 'https://assets.dedust.io/images/lucky.webp',
        decimals: 8,
    },
    {
        type: 'jetton',
        address: 'EQA2IyKaO7fKV37GxQGbRY_yZdE47ZdQXbOnX55OWhCwbL6H',
        name: 'GROK',
        symbol: 'GROK',
        image: 'https://assets.dedust.io/images/grok.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQATcUc69sGSCCMSadsVUKdGwM1BMKS-HKCWGPk60xZGgwsK',
        name: 'TON FISH MEMECOIN',
        symbol: 'FISH',
        image: 'https://assets.dedust.io/images/fish.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDODkpfxZ4joe3RxBckjgvCCQH-TXxozbNwTOoCUoOMCfX8',
        name: 'GRIMACE COIN',
        symbol: 'GRIMACE',
        image: 'https://assets.dedust.io/images/grimace.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCYlvFpi04AFebeF0x4KayKioExdvP23iwtTJ45GaaTTEbP',
        name: 'PAPA',
        symbol: 'PAPA',
        image: 'https://assets.dedust.io/images/papa.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDgHOW0gbfEodDilc8Vkms_FzahCxhXos7GwJXXhz8uwPET',
        name: 'Wrapped Ymakanic Coin',
        symbol: 'wYKC',
        image: 'https://assets.dedust.io/images/wykc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAtwmCISetV3ncZRb1QDiHcbSgfo-Y37-zPL6NhedGHGaTf',
        name: 'SEED',
        symbol: 'SEED',
        image: 'https://assets.dedust.io/images/seed.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBiHSLVzoicc-LQPDXJc_rF-WRft0aFihccFduA6fQ1ynYM',
        name: 'Baron',
        symbol: 'BARO',
        image: 'https://assets.dedust.io/images/baro.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCyfdVbfwkcBfBSn57GRnMY_BRO4vYG7HnkWngH41FLM-5Y',
        name: 'Making Money TON',
        symbol: 'MMT',
        image: 'https://assets.dedust.io/images/mmt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCMDE8Ffe-40QGryoSyazN_YlCHr-Hp_oc3-duz2GsaW-_w',
        name: 'TON GAIKA',
        symbol: 'GAIKA',
        image: 'https://assets.dedust.io/images/gaika.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC4D-qkAaqYXWOnWRJx6xtOhd7Fa9zZQdob8iWD6mS_kPqU',
        name: 'TONic',
        symbol: 'TONIC',
        image: 'https://assets.dedust.io/images/tonic.webp',
        decimals: 18,
    },
    {
        type: 'jetton',
        address: 'EQC_kG29HfgpJRW2RYIApeQI9PPYdzdsleqiarfo00MvSTSs',
        name: 'Meow',
        symbol: 'MEOW',
        image: 'https://assets.dedust.io/images/meow.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAcjv-v76upZgRoRNUM6tCmd6d9Q09sWVTFqCdfLeuP4P3b',
        name: 'TonTogether',
        symbol: 'TOT',
        image: 'https://assets.dedust.io/images/tot.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAjjnIVdwE6J0zgDXiXgOU5odFAvDE4iKvYDZx95wK17a8F',
        name: 'butTON',
        symbol: 'BTON',
        image: 'https://assets.dedust.io/images/bton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAJ29WkjjLqu-ucmAj9A0rRm86U6OvNRz46iqd1XVy8Pryq',
        name: 'Lombard Revival Token',
        symbol: 'LRT',
        image: 'https://assets.dedust.io/images/lrt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBBjMB-epcdooV0LKSAOl12see94OnllUWFXi0mqYZGsXr2',
        name: 'SIMBA',
        symbol: 'SIM',
        image: 'https://assets.dedust.io/images/sim.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDgyXtVBaUTYrNIYEyVTOIUCWItOPlj5eViJH7URrFI8DDR',
        name: 'BANANA',
        symbol: 'BANANA',
        image: 'https://assets.dedust.io/images/banana.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBE_P2bKO9dHGSwUhZbQv6va-YRuEWUEZuCv_iEXgO-psTz',
        name: 'Dracoin',
        symbol: 'DRA',
        image: 'https://assets.dedust.io/images/dra.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDf84FT8tdHZeI2-LXdb8gPMRqHRSABrmi8jI7MzvVpGJKZ',
        name: 'OpenCoin',
        symbol: 'OPEN',
        image: 'https://assets.dedust.io/images/open.webp',
        decimals: 5,
    },
    {
        type: 'jetton',
        address: 'EQADvGUQtbwXCgYU-0Ug4rGkwTpZr6Iyzikp6qMBpYE2HXFq',
        name: 'Mercury coin',
        symbol: 'MERC',
        image: 'https://assets.dedust.io/images/merc.webp',
        decimals: 7,
    },
    {
        type: 'jetton',
        address: 'EQDpnjfEwSJjdUufatHdopE9sZLKmD7ngXJvbixkel6zta5B',
        name: 'Chad on TON',
        symbol: 'CHAD',
        image: 'https://assets.dedust.io/images/chad.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD5ty5IxV3HECEY1bbbdd7rNNY-ZcA-pAIGQXyyRZRED9v3',
        name: 'Stable Metal',
        symbol: 'STBL',
        image: 'https://assets.dedust.io/images/stbl.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAO3n9xmdXwXHUhtZ3zKexpeUEKejYVKCeEupdsg2kvgcof',
        name: 'ToonTools',
        symbol: 'TOON',
        image: 'https://assets.dedust.io/images/toon.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB9D1_Rog6itYuNoLkIUmsjmkF7hU_UUSzFkEwiv6ZseCac',
        name: 'MAMA',
        symbol: 'MAMA',
        image: 'https://assets.dedust.io/images/mama.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD39LNnyg6uEQv5jqkF76F45VY4sszDqqz2N8KbL1QQ3XPr',
        name: 'BARASH',
        symbol: 'SHEEP',
        image: 'https://assets.dedust.io/images/sheep.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBlHnYC0Uk13_WBK4PN-qjB2TiiXixYDTe7EjX17-IV-0eF',
        name: 'Ton Invaders Coin',
        symbol: 'INC',
        image: 'https://assets.dedust.io/images/inc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAVluGRC4wEV2aDpiIgqiEvhnH--lmq5EFaL6C9Vfv0VRMZ',
        name: 'Fake Notcoin',
        symbol: 'FNOT',
        image: 'https://assets.dedust.io/images/fnot.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBmcXCytc9ZDcyfoh9FXNNvSkpsl_VD7GwjkhBU1hF1S_dw',
        name: 'DOBERCOIN',
        symbol: 'DOBER',
        image: 'https://assets.dedust.io/images/dober.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCDIJKFTf5QoWii6-_KTk8bo6eKiR-6hk5HUQwixCe8SW-I',
        name: 'VISHNYA',
        symbol: 'VISHNYA',
        image: 'https://assets.dedust.io/images/vishnya.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCA4a0fi5CCkKowfZVASYOcaz9nJhhWI7DijU2vsohyMGNn',
        name: 'JogjaTON',
        symbol: 'JOG',
        image: 'https://assets.dedust.io/images/jog.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC47093oX5Xhb0xuk2lCr2RhS8rj-vul61u4W2UH5ORmG_O',
        name: 'Gram',
        symbol: 'GRAM',
        image: 'https://assets.dedust.io/images/gram.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCsN1IslttnFpGjUabpt3RCnVYca74ZB9yD0L2ZK9CvJ53D',
        name: 'Ferma Invest Dom',
        symbol: 'FID',
        image: 'https://assets.dedust.io/images/fid.webp',
        decimals: 3,
    },
    {
        type: 'jetton',
        address: 'EQBfX9KO5yIFprHWPpJp3OsX-6cjLjEJF-h5uIQE3eLJY8_h',
        name: 'Virtuals Worlds',
        symbol: 'VWS',
        image: 'https://assets.dedust.io/images/vws.webp',
        decimals: 18,
    },
    {
        type: 'jetton',
        address: 'EQA1jvPqRx6bujYohDny43hwX8FZr3b6OYnI3t2jHd4TXSJs',
        name: 'TON SHIP',
        symbol: 'SHIP',
        image: 'https://assets.dedust.io/images/ship.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCweXSZaX5k5xOtXLbGgfF8FY6Dbg6rNiPrd9d0f_-kDSHZ',
        name: 'RubeTON',
        symbol: 'RUBETON',
        image: 'https://assets.dedust.io/images/rubeton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBtcL4JA-PdPiUkB8utHcqdaftmUSTqdL8Z1EeXePLti_nK',
        name: 'Web3 TON Token',
        symbol: 'WEB3',
        image: 'https://assets.dedust.io/images/web3.webp',
        decimals: 3,
    },
    {
        type: 'jetton',
        address: 'EQCymLRXp1QYxZKek4CTInckB1ey5TkyAJQpPAlNetiO54Vt',
        name: 'Meridian',
        symbol: 'MRDN',
        image: 'https://assets.dedust.io/images/mrdn.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD3U8yc2moTe8yCbUlYxkMh_SCCWLkuxQam2lab4iDfpXYU',
        name: 'Secure Sockets Layer',
        symbol: 'SSL',
        image: 'https://assets.dedust.io/images/ssl.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBHcVEoIwZ22GifL7BtVTGkzJKLQoC-rmqV6_nj7SR-hL2P',
        name: 'Jason Statham',
        symbol: 'STATHAM',
        image: 'https://assets.dedust.io/images/statham.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC8FoZMlBcZhZ6Pr9sHGyHzkFv9y2B5X9tN61RvucLRzFZz',
        name: 'JVault Token',
        symbol: 'JVT',
        image: 'https://assets.dedust.io/images/jvt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDmgVHxf-avCIDyU3POfqzXsyU9FzAOdJGVAY-arolFtb7B',
        name: 'TonEnd',
        symbol: 'END',
        image: 'https://assets.dedust.io/images/end.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDNlNA2NSbWtigW37WX__FIu4Y2NNPwijJd3Ktmhi7gdCyv',
        name: 'E4',
        symbol: 'E4',
        image: 'https://assets.dedust.io/images/e4.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDnNof1yihA_JtXc70AZJCgw5_b1hIKkJGcdBXS5K-p3S-_',
        name: 'Tonbet Token',
        symbol: 'TBT',
        image: 'https://assets.dedust.io/images/tonbet.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBT2Ee4Lx5w9uI7oMly5upXNs3ABWL_Fwk1uiM74gZCGaYt',
        name: '1RUS DAO',
        symbol: '1RUSD',
        image: 'https://assets.dedust.io/images/1rus.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDgSR_-4FDlXPfMVefXX1IIXMWBH4YfYV1a_8cJ0XsGVdsf',
        name: 'PROTON JETTON',
        symbol: 'PROTON',
        image: 'https://assets.dedust.io/images/proton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC52I3c2rmZpUav0LrU6q7wuXoTmhOInvaFhKjZ6QuC5tV5',
        name: 'SCAM',
        symbol: 'SCAM',
        image: 'https://assets.dedust.io/images/scam.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAu8oDM_dXMgQd1COjRnU6sYhmvm5RP32gyyL9R2Rv-8s70',
        name: 'SquirellCoin',
        symbol: 'SQRL',
        image: 'https://assets.dedust.io/images/sqrl.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBLhoan0aTiLK6JTys13c8ZM1qjqpDFOs3UpYQ0B-Kdt3J6',
        name: 'BRAD',
        symbol: 'BRAD',
        image: 'https://assets.dedust.io/images/brad.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCXIHAWDAJEJhMiNVqeUvp3I6O7y_P2sD80zEsJXeUi56mb',
        name: 'Mumba',
        symbol: 'MUMBA',
        image: 'https://assets.dedust.io/images/mumba.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBfMGkJtSWA4VZspN0zC9iedpK60HwPAIEWaPJaIWgf_pnV',
        name: 'TON Goblins Token',
        symbol: 'GOBLIN',
        image: 'https://assets.dedust.io/images/goblin.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCRU1SC3xNf_r33q8NZzLughmvdE21JRYIZj4oRKUdRKRDb',
        name: 'BEETON',
        symbol: 'BEE',
        image: 'https://assets.dedust.io/images/bee.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD4P32U10snNoIavoq6cYPTQR82ewAjO20epigrWRAup54_',
        name: 'Hydra',
        symbol: 'HYDRA',
        image: 'https://assets.dedust.io/images/hydra.webp',
        decimals: 6,
    },
    {
        type: 'jetton',
        address: 'EQDzvs6ZhNDZMQMeKK2Inc8ymDpORl0H5hAfgtf3dXRbt7I7',
        name: 'Rug Pull',
        symbol: 'RUGPULL',
        image: 'https://assets.dedust.io/images/rugpull.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDAiXxX8J2CHo4un2mAYFuexI620Y33CWfLFZK-7LcR9Pps',
        name: 'Magic Vip People',
        symbol: 'MVP',
        image: 'https://assets.dedust.io/images/mvp.webp',
        decimals: 18,
    },
    {
        type: 'jetton',
        address: 'EQDA6v7olSvZCEr2yNhUlM4eBnRF11lsHLrtkkh7MSMICt4r',
        name: 'SAFT ENRG',
        symbol: 'SENRG',
        image: 'https://assets.dedust.io/images/senrg.webp',
        decimals: 0,
    },
    {
        type: 'jetton',
        address: 'EQCY8WgTgujVGm83VZyFUuFIXuD9_SAKwGyiJiBuxGq55DGd',
        name: 'Tilt',
        symbol: 'TILT',
        image: 'https://assets.dedust.io/images/tilt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD3zalQrwnhAA5puG-J_tQv3W5n5c6v449jk084Bq4lWuSQ',
        name: 'Ton Ai',
        symbol: 'TAI',
        image: 'https://assets.dedust.io/images/tai.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQByLZOaBbpr9EwNonXKEfkkZL1viNsYHezxw5CVK4Bh0zEb',
        name: 'DINJA',
        symbol: 'DINJA',
        image: 'https://assets.dedust.io/images/dinja.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDsvbmh_rHjpO-FX3pmtPutllynl0OKuqqR9c1RICibsN6l',
        name: 'Round Chicken Token',
        symbol: 'RCT',
        image: 'https://assets.dedust.io/images/rct.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDlnVo-6abJzyHlU8uB7pRjE7OIKt4HTTDPG4hfwOf5jTPg',
        name: 'ALL',
        symbol: 'ALL',
        image: 'https://assets.dedust.io/images/all.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAMSx9XLYJ6lYB9LL0kAPjZPhGYdlV7QQsPgRrVGv3qGLNt',
        name: 'Stec Network',
        symbol: 'STEC',
        image: 'https://assets.dedust.io/images/stec.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQATgD7dao9jWBdz_qKL-UJZCXZGQvV5HJVUC85ssgmHKWll',
        name: 'Plankton',
        symbol: 'PLANKTON',
        image: 'https://assets.dedust.io/images/plankton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDsrCYtZgbO57PQ47b9oytjQrUjix-gz2wIP088DEUvh2kC',
        name: 'ARBUZ',
        symbol: 'jARBUZ',
        image: 'https://assets.dedust.io/images/arbuz.webp',
        decimals: 18,
        source: {
            chain: 'eip155:1',
            address: '0x10ba2e5ac2e91d5a89fe0f89bb625ebcefff812d',
            bridge: 'ton-bridge',
            symbol: 'ARBUZ',
            name: 'ARBUZ',
        },
    },
    {
        type: 'jetton',
        address: 'EQBZ_cafPyDr5KUTs0aNxh0ZTDhkpEZONmLJA2SNGlLm4Cko',
        name: 'Resistance Dog',
        symbol: 'REDO',
        image: 'https://assets.dedust.io/images/redo.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBhj9Fwtr0ZwftDF13f6d1aqh5Cegdqit8BCTwbjL71KN3Z',
        name: 'FREEDOM',
        symbol: 'FREE',
        image: 'https://assets.dedust.io/images/free.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB2lbt2s_jdUW3OoUIb7-9RoK2UeGXmgC7BnOwgK6P_JTrm',
        name: 'UNICORN',
        symbol: 'UNIC',
        image: 'https://assets.dedust.io/images/unic.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCgFCvZCV6qqB-2Kel6D_kV4zEW4FFOQfYV4KDDNTEJdItn',
        name: 'BORIS PIXEL',
        symbol: 'PIXEL',
        image: 'https://assets.dedust.io/images/pixel.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCSn3u5g0mGg4eBnP36kauDc9Flt4VphS-0TXz0f60wOqsI',
        name: 'eNOT COIN',
        symbol: 'eNOT',
        image: 'https://assets.dedust.io/images/enot.webp',
        decimals: 5,
    },
    {
        type: 'jetton',
        address: 'EQCIIUm7dnBgmcrubDfFLZV52oe1F_HFdDZiMfer9riphpQo',
        name: 'SAKE',
        symbol: 'SAKE',
        image: 'https://assets.dedust.io/images/sake.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCcXKwYGCCZnzQj9vwwg8Y-F3d8H7cow-Mwgj8pTFruBfP8',
        name: 'Tribe',
        symbol: 'TRIBE',
        image: 'https://assets.dedust.io/images/tribe.webp',
        decimals: 2,
    },
    {
        type: 'jetton',
        address: 'EQBygwrEcGIj5zmEtWeMGsQXbXr1WBgV3coVfqyURQighw2Y',
        name: 'NUDES Coin',
        symbol: 'NUDES',
        image: 'https://assets.dedust.io/images/nudes.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDoziSttQZ96QJRxHRKdatCm5L9DRL9LKycXcjl8RPXZM0N',
        name: 'POT',
        symbol: 'POT',
        image: 'https://assets.dedust.io/images/pot.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCvsARFU_tJCRq7eFTrs2ORasCwDIPLQo7ZlkehsMmgQzd8',
        name: 'OAAL AI',
        symbol: 'OAAL',
        image: 'https://assets.dedust.io/images/oaal.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCHrhcBGVVlre8ngBlxLtfte37OGsXeJSmFSmABL8x44QH2',
        name: 'The Open SOFT',
        symbol: 'SOFT',
        image: 'https://assets.dedust.io/images/soft.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD_ETL-SQRFwuxIIDwvo8CiwuVK9o7lXgfNVUSz9tllGMz9',
        name: 'DYNYA',
        symbol: 'DYNYA',
        image: 'https://assets.dedust.io/images/dynya.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBTcytZjdZwFLj6TO7CeGvn4aMmqXvbX-nODiApbd011gT3',
        name: 'Duck Coin',
        symbol: 'DUCK',
        image: 'https://assets.dedust.io/images/duck.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCOGp1GAVk51prVBw5DO8QN3lKIlUJKjXbZcl5aXgL5hkwy',
        name: 'Wrapped NANO',
        symbol: 'jNANO',
        image: 'https://assets.dedust.io/images/jnano.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCL6jaTluAI7ET_JgZ3hPV9Ul8MXP2mZWhMQtGMzd-cNt-X',
        name: 'Ptah',
        symbol: 'Y',
        image: 'https://assets.dedust.io/images/y.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAHBPL5Q51kQWMtItT3buuaDz0s_Bq4kN174-RKtlqOu07o',
        name: 'Rocket Cats',
        symbol: 'RCAT',
        image: 'https://assets.dedust.io/images/rcat.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCy_Zo_ahdCCcDyGQazuAVKWa8KSW930j1VI8k9ZQJYB4_V',
        name: 'SybilZero',
        symbol: 'jSYBZERO',
        image: 'https://assets.dedust.io/images/jsybzero.webp',
        decimals: 18,
    },
    {
        type: 'jetton',
        address: 'EQAORkhhrXis_XxLAAfyxTyNceNXLtaHcJ5FhXxpNJ8xsDGc',
        name: 'bemo Staking Experience Point',
        symbol: 'stXP',
        image: 'https://assets.dedust.io/images/stxp.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB3421IebxFlcxNYWzRkY9UK7wRaOsWEoO8u2hppdc1AHg9',
        name: 'NOTSHIBA INU',
        symbol: 'NOTSHIB',
        image: 'https://assets.dedust.io/images/notshib.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQChXgdfER2nuLvZP5EiSlCf95oXZ5KDiCEmGBBv_WcNdxz3',
        name: 'Pavul Durkev',
        symbol: 'PAVUL',
        image: 'https://assets.dedust.io/images/pavul.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAEBhAUSSJ_NqYJO3WRNkBUMpfAf7hnd9X7WBhZSqLaxYko',
        name: 'TPLANT',
        symbol: 'TPLANT',
        image: 'https://assets.dedust.io/images/tplant.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD8_ro5tJDyWm0avPITefZ-9ZkzQ9GRvAaKWLX1SkDKTGUt',
        name: 'BEGEMOTIK',
        symbol: 'HIPPO',
        image: 'https://assets.dedust.io/images/hippo.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBfl_pzi8t_fYXJEygZoz8cId1sdjnPTsBpvqiHjggXS3Ep',
        name: 'Kartoshka',
        symbol: 'POTATO',
        image: 'https://assets.dedust.io/images/potato.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCZaonjafRJMGz98bItlACMBLh17Y3bMftkppmebJm2O92Z',
        name: 'OTTON',
        symbol: 'OTN',
        image: 'https://assets.dedust.io/images/otton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBaOSt5XIqPJjJuHfiK1ZZ7VMpE6VZhwJodY_qnK9qIRAUh',
        name: 'Not Floki Ton',
        symbol: 'NFTON',
        image: 'https://assets.dedust.io/images/nfton.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAJZElrDTgkt0exICrVUQPjN19knWOniGsJC_AunyqfPA0w',
        name: 'SafeMars',
        symbol: 'SFMT',
        image: 'https://assets.dedust.io/images/safemars.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQA7nLJI-Eoc5oBzEBnlLzezTEwGNRvyR5tX7iWHT8KPwVy1',
        name: 'TON7DAO',
        symbol: 'TON7DAO',
        image: 'https://assets.dedust.io/images/ton7dao.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB8RNC7E-0uWcfSP68rk_RReN2JYKQ4nBLq1RsKpaVme0xx',
        name: 'Rotgar',
        symbol: 'ROTGAR',
        image: 'https://assets.dedust.io/images/rotgar.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAty7cyLIjF7U-K0VgG_gcksTAKtILkbJCNjPYlZ85cCZAA',
        name: 'SAUD',
        symbol: 'SAU',
        image: 'https://assets.dedust.io/images/saud.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDPdq8xjAhytYqfGSX8KcFWIReCufsB9Wdg0pLlYSO_h76w',
        name: 'Hipo Staked TON',
        symbol: 'hTON',
        image: 'https://assets.dedust.io/images/hton.webp',
        decimals: 9,
        source: {
            chain: 'eip155:1',
            address: '',
            bridge: 'none',
            symbol: 'hTON',
            name: 'Hipo Staked TON',
        },
    },
    {
        type: 'jetton',
        address: 'EQAmXCLQN6PcgKMhK91_bAPqbSvyiCw4eZRAIStkSi7fUaRA',
        name: 'Goy Token',
        symbol: 'GOY',
        image: 'https://assets.dedust.io/images/goy.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCnhewfpFblzaE-pQpXxHSRgNz7R_YrF1YoAS8HFpwfH6XI',
        name: 'Roosty',
        symbol: 'ROOSTY',
        image: 'https://assets.dedust.io/images/roosty.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQD7THgw9GZ7udZzjzwiBXMHEKSCHiElKEHjn_-lcXoGApel',
        name: 'xCryproMarket',
        symbol: 'XCM',
        image: 'https://assets.dedust.io/images/xcm.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAuco5ZEPgB19fSTo7EmtLTJysrKxbu6M_XOFDwWQiNjCsQ',
        name: 'DOGWIFHOOD',
        symbol: 'WIF',
        image: 'https://assets.dedust.io/images/wif.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDQEsrlf5ALa7-Gpz2nDK6t332bcyQoP0BzHj2KKTrXYVYB',
        name: 'REKT',
        symbol: 'REKT',
        image: 'https://assets.dedust.io/images/rekt.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC7rnHHtMVBKyhiGnAbtYIlzGxS0dfi3ZbHExFX0LYi9cAH',
        name: '@BTC25',
        symbol: 'BTC25',
        image: 'https://assets.dedust.io/images/btc25.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQA79IISXMR8ve9AOipUE3i5htp6z6I7ynSC9DKBo8zHsIYr',
        name: 'MagicDeer',
        symbol: 'DEER',
        image: 'https://assets.dedust.io/images/deer.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDK3ReFkb6L3uE3GmMDJaxWby4PA_UYGClgFfJuXY52-TOK',
        name: 'Slowpoke',
        symbol: 'SLOW',
        image: 'https://assets.dedust.io/images/slow.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQARmDybfEvyI_r3JW7zZAV-VTz8pWvseuIWpjYqQA44ui9r',
        name: 'FlokiTon',
        symbol: 'FLOKIT',
        image: 'https://assets.dedust.io/images/flokit.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAzqUYA_QbvX2GkUaUu6wl6TTcwy5gytvUp2gqw9FVTLGfY',
        name: 'GOPNIK CATS',
        symbol: 'KORM',
        image: 'https://assets.dedust.io/images/korm.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCtnNdPnA4NTt4XQ_M21dKyoUR7da_SX7uqtO-wh1HeqsX4',
        name: 'indicaTon',
        symbol: 'ICTN',
        image: 'https://assets.dedust.io/images/ictn.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBB-EMREJkIHVYG5DPiklOhWPcsCaxjL9HKmgRvuGtz_1lu',
        name: 'Nobby Game',
        symbol: 'SOX',
        image: 'https://assets.dedust.io/images/sox.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDdKkzOKps7IlK0Fv4EJmHDIvOZQ7LtsCa-ve4qJpopF4oq',
        name: 'CookieToken',
        symbol: 'COOKIE',
        image: 'https://assets.dedust.io/images/cookie.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCgW3iMiYqkqBjqYR391w525-3pnFzVstHlbZ4dkulW_oz5',
        name: 'MiDtoken',
        symbol: 'MID',
        image: 'https://assets.dedust.io/images/mid.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDoqIKkOevVZukmf1L8nGhcjlha4sfvgl8GIRpTj_b53HyR',
        name: 'Pizza Gram',
        symbol: 'PIZZA',
        image: 'https://assets.dedust.io/images/pizza.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAl0ChJyynGWg0tGMCBM6soeKJrKtNm_IATf17jcFEQx0Ww',
        name: 'povel durev (old)',
        symbol: 'DUREVOLD',
        image: 'https://assets.dedust.io/images/durev-old.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB02DJ0cdUD4iQDRbBv4aYG3htePHBRK1tGeRtCnatescK0',
        name: 'povel durev',
        symbol: 'DUREV',
        image: 'https://assets.dedust.io/images/durev.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBN2iDBrdAVRXz95RJbcftDCYZYDZmiWB4cbyZDj8h7Xn6c',
        name: 'Billionaire Boys Club',
        symbol: 'BBC',
        image: 'https://assets.dedust.io/images/bbc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBzX9AKtu4EPjHcK9KJ6dytJUjllgR_BUTHkBwDA8gkvK2l',
        name: 'Memecoin',
        symbol: 'MEME',
        image: 'https://assets.dedust.io/images/meme.webp',
        decimals: 2,
    },
    {
        type: 'jetton',
        address: 'EQDQ2oBzTO4Itn9mmu3TL1v5TUiPS9PuAIVEq1xMpLHeeEsI',
        name: 'Only one token',
        symbol: 'NANO',
        image: 'https://assets.dedust.io/images/nano.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQA9dayEKflrL-wIf-GKGizj26pvX0QCIxwmRgqzg5U_c3YB',
        name: 'Coffee',
        symbol: 'COFE',
        image: 'https://assets.dedust.io/images/cofe.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDv-yr41_CZ2urg2gfegVfa44PDPjIK9F-MilEDKDUIhlwZ',
        name: 'ANON',
        symbol: 'ANON',
        image: 'https://assets.dedust.io/images/anon.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBenWCdMBAILriH8yPX9bfmjcZlmer1JgRDHDWblDK13TOp',
        name: 'ChipiCoin',
        symbol: 'CHAPA',
        image: 'https://assets.dedust.io/images/chapa.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBtv7I3pZpMAUChef2Vrk-U1GcCE00rROuHgMJ9CvjodRZW',
        name: 'Bear Coin',
        symbol: 'BEAR',
        image: 'https://assets.dedust.io/images/bear.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAVw-6sK7NJepSjgH1gW60lYEkHYzSmK9pHbXstCClDY4BV',
        name: 'meh',
        symbol: 'MEH',
        image: 'https://assets.dedust.io/images/meh.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBTUH6cdozp2TWujAqamNjgmCrXcV7FraQ6KieDu7pYsMjm',
        name: 'DEANON',
        symbol: 'DEANON',
        image: 'https://assets.dedust.io/images/deanon.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAhPcpyfkhv2MPUxYm37g-NjZpBrp-hO-XEpOVkgOLAE2hS',
        name: 'Pun Dog',
        symbol: 'PUN',
        image: 'https://assets.dedust.io/images/pun.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAEfUNvB01k3khyyMJeQu6Y609TOPtm_-Mn0-12NJb4SXwR',
        name: 'Infinity',
        symbol: 'INFT',
        image: 'https://assets.dedust.io/images/inft.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBXP-cvi8iocxZ4mooU_RzT6P7znZoQ1BDGCxpuEvrczL95',
        name: 'Ryan Gosling',
        symbol: 'GOSLING',
        image: 'https://assets.dedust.io/images/gosling.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCtxbfa9bVXn7wsfK5V72fX1RFuc8kFDF7piMioWENgEBx5',
        name: 'SquidTG',
        symbol: 'SQD',
        image: 'https://assets.dedust.io/images/sqd.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQA6Y0rWysG4HWmros7V-z7NrjErvyCwvNVFlvyEjLHv5PJe',
        name: 'Squid Egg',
        symbol: 'SQG',
        image: 'https://assets.dedust.io/images/sqg.webp',
        decimals: 0,
    },
    {
        type: 'jetton',
        address: 'EQB087W3GWe2FIJPgoyI30Mf5d1hNBfqLc2s7wFTJJsX6qY_',
        name: 'Ruslon Skamolovsky',
        symbol: 'RUSLON',
        image: 'https://assets.dedust.io/images/ruslon.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBam5RuB3inYXsUlamTIEqu-tNy5NmX4FBLAcZe_360eWWE',
        name: 'Ton Hamster',
        symbol: 'HMSTR',
        image: 'https://assets.dedust.io/images/hmstr.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCXzO7HhoK5fDQuCONE43l8-Qsreq5zq89ZVNhEna24eK-h',
        name: 'PEPE TON',
        symbol: 'PEPE',
        image: 'https://assets.dedust.io/images/pepe.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQARb2CYeCT73K-a_cWXycgbcWlleEx4fq4RCbZ7cWBtPN8s',
        name: 'BOLTWIFSOCK',
        symbol: 'SOCK',
        image: 'https://assets.dedust.io/images/sock.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB9e2RJaJnX_tALDBSyIb5oj0YHJLa8FncsF-5MjXolbUzC',
        name: 'GM',
        symbol: 'GM',
        image: 'https://assets.dedust.io/images/gm.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCDkrpCu-FFVPQJnManjlf8XCN75wjX_AKrrEFFQ1mfJqZo',
        name: 'Yoken',
        symbol: 'YO',
        image: 'https://assets.dedust.io/images/yo.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAWpz2_G0NKxlG2VvgFbgZGPt8Y1qe0cGj-4Yw5BfmYR5iF',
        name: 'Not Meme',
        symbol: 'MEM',
        image: 'https://assets.dedust.io/images/mem.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBdr5b7csZbXhDnQ5U364bpLylHfk8AWcug8TwhzCMVcvPA',
        name: 'Rosecoin',
        symbol: 'ROSE',
        image: 'https://assets.dedust.io/images/rose.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAaJybAsdcXbeW_PsrQZElZWE4x8mLkL9s58kIc0OtpCWFO',
        name: 'TON Degen',
        symbol: 'DGN',
        image: 'https://assets.dedust.io/images/dgn.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDHl2sVhrY4lvdHFLzuSvGogXuSim206UvXHNwFR88hCiyh',
        name: 'Salo',
        symbol: 'SALO',
        image: 'https://assets.dedust.io/images/salo.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCcYUWKhjGxwqtk_je9LW2V4RoFmbhOUR9e404Y6FQTEXHh',
        name: 'The Resistance Girl',
        symbol: 'REGI',
        image: 'https://assets.dedust.io/images/regi.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBhRoPmOImcU2e3CLKD6eCZ_PfOz2iYFcOY3139HUUx0phP',
        name: 'Dubai #2049',
        symbol: 'DUBAI',
        image: 'https://assets.dedust.io/images/dubai.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQAzBy-W8GJjUPfU-8eV0Jz56Jc5dIvvP-qznHKQhlqzGkoZ',
        name: 'AIYA PowerCell',
        symbol: 'APC',
        image: 'https://assets.dedust.io/images/apc.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBphnWv7EkQvjIkGPjMNacYtXo2dEqFIybPTf8IxyBGjNSz',
        name: 'Dogecoin TON',
        symbol: 'DOGE',
        image: 'https://assets.dedust.io/images/doge.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQC7zE2BVcLiybBMuQ1giOPYmO4Ji88J12r7duqMJWOtFxtr',
        name: 'Epidemy',
        symbol: 'VIRUS',
        image: 'https://assets.dedust.io/images/virus.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQCTWKZUR3BlJ-jnT_GE8RtERDOMQ1los7-Up3ipQkTi700i',
        name: 'Capybara',
        symbol: 'CPBR',
        image: 'https://assets.dedust.io/images/cpbr.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB8T1ylyks0DFFkUUC2KeFlzXMm-xDjvv6wDDRXLr6jTPRz',
        name: 'PUGWIFJET',
        symbol: 'PWJ',
        image: 'https://assets.dedust.io/images/pwj.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDdCha_K-Z97lKl599O0GDAt0py2ZUuons4Wuf85tq6NXIO',
        name: 'Du Rove’s Wall',
        symbol: 'WALL',
        image: 'https://assets.dedust.io/images/wall.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBc-L5CzzRKmR3-TdOwBm4l-XyJdxJt3HfAIr_qMiKaB7WM',
        name: 'DEPOSIT',
        symbol: 'DEPOSIT',
        image: 'https://assets.dedust.io/images/deposit.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDNJzbNKA8Ix2X7Tv1_jxdCqehPQgJaNbisoIkSq5srnfLs',
        name: 'Burncoin',
        symbol: 'BURN',
        image: 'https://assets.dedust.io/images/burn.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQDWuR1l5EbiGPf2_7VK0davJ6bkXwi4STx8VfaMqrJkd0tm',
        name: 'Diablo Gato',
        symbol: 'GATO',
        image: 'https://assets.dedust.io/images/gato.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQB0apV-NyCYJDVwSBoDL86Xjp0OiwcyD8jJ0J5BVWnnDJu7',
        name: 'OPEN',
        symbol: 'OPEN',
        image: 'https://assets.dedust.io/images/open-1.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAOLOJ9jhS1RmzEQwayCcD_8glZhI3m7lNOfoNTUhP4Ta8n',
        name: 'adDICKted',
        symbol: 'DICK',
        image: 'https://assets.dedust.io/images/dick.webp',
        decimals: 9,
    },
    {
        type: 'jetton',
        address: 'EQBecg3E6822M1aZOZhqzMWaSRGP712sDRkQgHO4MSgDRDHq',
        name: 'INSECT',
        symbol: 'INS',
        image: 'https://assets.dedust.io/images/ins.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAdz16aPWCmAYldTiX_g-NRzT-spbN8tCk9dJIHfAiC3L4p',
        name: 'CARDIFY Coin',
        symbol: 'CRDF',
        image: 'https://assets.dedust.io/images/crdf.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDBrZm6Gkh8s3Y92NfUKh71ZwhKZmZw0IgE1j3e6ZAfuqbd',
        name: 'SHIC Coin',
        symbol: 'SHIC',
        image: 'https://assets.dedust.io/images/shic.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQApavswugkXNSg2pKxIQXczMOjZc2Mg0t3j_KuCmSBRBTBw',
        name: 'PUPA',
        symbol: 'PUPA',
        image: 'https://assets.dedust.io/images/pupa.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBXRzatxryKKnW6mNGEZiEFMGET655W40ROx1qnZP-S_-p6',
        name: 'LUPA',
        symbol: 'LUPA',
        image: 'https://assets.dedust.io/images/lupa.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAjQBt5h8SzLugDGp-75IiePuddLU32FGR4H3F3zPSLw7oL',
        name: 'TLB500 Index',
        symbol: 'TLB500',
        image: 'https://assets.dedust.io/images/tlb500.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDJXgXvdkTCG0N6-e6B1-fl1U1LnPHMYpqio3UEA9KAZ07j',
        name: 'LLAMA',
        symbol: 'LLAMA',
        image: 'https://assets.dedust.io/images/llama.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBCoynGYslAMjv_gRl_2_B1KMOvh9ZW-ae0p7SaXZy6KFjY',
        name: 'GoiCoin 2',
        symbol: 'GOI',
        image: 'https://assets.dedust.io/images/goi-2.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDWEsV8ZD83HhpJBLWuB_r55XLwNCpZwcBo-UGNthcJtboi',
        name: 'ARUTCOIN',
        symbol: 'ARUT',
        image: 'https://assets.dedust.io/images/arut.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB4gPfG0YtoiJHCMTUuzxP9fKXy9nx6TFh-dcAltrnNpLNo',
        name: 'Shitcoin',
        symbol: 'SHIT',
        image: 'https://assets.dedust.io/images/shit.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB2ho8cuNzitlhg_H29pOHUxRD-VlxvIbN0ZVORNh8REGre',
        name: 'Donut The Dog',
        symbol: 'DONUT',
        image: 'https://assets.dedust.io/images/donut.webp',
        decimals: 6,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB-i1kqPz_MitkRCOzzgDf0_doxahk1bUPVAGjm49zMozOd',
        name: 'Ton Croco',
        symbol: 'CROCO',
        image: 'https://assets.dedust.io/images/croco.webp',
        decimals: 6,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCObh4-ZaghOva8uCz_AMMnvifM3PS-EppUJEJQXXnlP0zX',
        name: 'Whiskers',
        symbol: 'WHISK',
        image: 'https://assets.dedust.io/images/whisk.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDByR6xbRrTWIQFKfeBIjkIWLvnrlenGV97kiV3sEXRpT8E',
        name: 'Outback Jack',
        symbol: 'JACK',
        image: 'https://assets.dedust.io/images/jack.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDVkOpW-r6RiRYSpGRKnVvvf8YQkA-X9ZLZxtddaQldVzg6',
        name: 'Ton Cuphead',
        symbol: 'TONCUP',
        image: 'https://assets.dedust.io/images/toncup.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDtqSANqK4LqgDk4f_q9mIvOaVy212ulavP9em2eYwKOiJw',
        name: 'DAOLegion',
        symbol: 'LGN24',
        image: 'https://assets.dedust.io/images/lgn24.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBwJaB-51Efd1CraJskTAkx2NDZHf71ONWUlJl-KIGOzs4b',
        name: "Telegram's Dog",
        symbol: 'REMY',
        image: 'https://assets.dedust.io/images/remy.webp',
        decimals: 6,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAejag_GBPBdSpVZGcWrSQuZmDQxaYJCsHzB0RQTeyEa0Nh',
        name: 'JETMOON',
        symbol: 'JMT',
        image: 'https://assets.dedust.io/images/jmt.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD2OT38svz8BF_c4OVPMV83uuNnjlDJ3vfKSpMwq-r-b1Bq',
        name: 'MARIO',
        symbol: 'MARIO',
        image: 'https://assets.dedust.io/images/mario.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB4vbSuNkcvZiq0Z-XA3bVCfN5hj5cBivFJA9pPCtOotAfE',
        name: 'RULO CMO',
        symbol: 'RULO',
        image: 'https://assets.dedust.io/images/rulo.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBwy-wJ-wCqh0mfJHoWjmulJ0oIRKEJJt75ULyrJNPcnn5z',
        name: "Telegram's Cat",
        symbol: 'MITTENS',
        image: 'https://assets.dedust.io/images/mittens.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQA4YM9cFn4swQUfF9BgUFb7UDYs7hfWG9rMhXUn6Wp1G0Kx',
        name: 'FUCK MORGENSHTERN',
        symbol: 'FKMORGEN',
        image: 'https://assets.dedust.io/images/fkmorgen.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD5rGGgViI16nT5nL0auCwZlTPCbwCOIjNkIx1oLW12tFgo',
        name: 'Volodemer',
        symbol: 'PUTEN',
        image: 'https://assets.dedust.io/images/puten.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDhnXQgjkymx2DgbcLZqvLClyBEsFAAr-RotkrXhf1OD3Gp',
        name: 'Andy',
        symbol: 'ANDY',
        image: 'https://assets.dedust.io/images/andy.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBZGBxlhSpBzQfFdj7AqJa6tIavsCaFBYDl2C5J5TIFecrH',
        name: 'Ton Trump',
        symbol: 'TRUMP',
        image: 'https://assets.dedust.io/images/trump.webp',
        decimals: 6,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBcZmaHu2Q5e9rGFMntm-8U1s7O-IV2zDoj0naJ02lbNnlC',
        name: 'AIMLAB',
        symbol: 'AIM',
        image: 'https://assets.dedust.io/images/aim.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDeXL9S-ApGesQUbBLYi2RGS9UpWfABGAF8jEDh_6XQjOR6',
        name: 'Melon',
        symbol: 'MELON',
        image: 'https://assets.dedust.io/images/melon.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBFDgg6O1_iZoOqSgZanzQ99jI0tRpeClSZxrDU_o2zvRX5',
        name: 'NOTGEM',
        symbol: 'NOTGEM',
        image: 'https://assets.dedust.io/images/notgem.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQABBW_uifkTMvvR0PHq3NoNHDTDoEgSMToU8oaTkO-Hif5A',
        name: 'Ape by Ton',
        symbol: 'TAPE',
        image: 'https://assets.dedust.io/images/tape.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCcEQH9OHZtygJpWAaFiYu-OoEVQjSJz6Dy_0U9hEySyO4U',
        name: 'WINKO',
        symbol: 'WINKO',
        image: 'https://assets.dedust.io/images/winko.webp',
        decimals: 0,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD-LW9jU2btSu_clrc-cXJaHJS6LKJ69QMcpLbFFPUxc4Ux',
        name: 'Nikolai KOT Durov',
        symbol: 'KOT',
        image: 'https://assets.dedust.io/images/kot.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDxRD-NX0xtsu2id0tufZLdxBNoiKkzjAQqBh65Zxq2IK48',
        name: 'Baby Notcoin',
        symbol: 'BBNOT',
        image: 'https://assets.dedust.io/images/bbnot.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDOrg1GXObvpLoQSpnGxcb5wA42-V2CcFl6Pr25sVoJVmTv',
        name: 'Hmmcoin',
        symbol: 'HMM',
        image: 'https://assets.dedust.io/images/hmm.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAvlWFDxGF2lXm67y4yzC17wYKD9A0guwPkMs1gOsM__NOT',
        name: 'Notcoin',
        symbol: 'NOT',
        image: 'https://assets.dedust.io/images/not.webp',
        decimals: 9,
        aliased: true,
    },
    {
        type: 'jetton',
        address: 'EQC5zvSRzDAtL-kou3HpyVbOV_w-202wJi6Y0DwAM7GKmfCY',
        name: 'NUTCOIN',
        symbol: 'NUT',
        image: 'https://assets.dedust.io/images/nut.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCF9oYxo37xCGX1DShZEweaVGJe6Kucp0ztKO6vCsRANDOM',
        name: 'Random.tg',
        symbol: 'RANDOM',
        image: 'https://assets.dedust.io/images/random.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCILWMtTu_ShFu0WPZnZx9SfCX70dTypBESubKMZUPQOd53',
        name: 'GPU — M2M coin',
        symbol: 'GPU',
        image: 'https://assets.dedust.io/images/m2m.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBa4nrNBX2LtJemhMXxkMPQpmCKNlt536SVleo1TYwcSdP7',
        name: 'Russia Mascot',
        symbol: 'MASCOT',
        image: 'https://assets.dedust.io/images/mascot.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAaGlxC31YlSxzK_9hG3ka6UN1G9hbhXJI3STtfURHhIvsu',
        name: 'TONY',
        symbol: 'TNY',
        image: 'https://assets.dedust.io/images/tony.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBeJxQ0mf54_wg3dSJzE6I44YorvVCHrjLSRTTkVdjL2VYj',
        name: 'TON BOGE MEMECOIN',
        symbol: 'BOGE',
        image: 'https://assets.dedust.io/images/boge.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDqrKJj1ZQeGTHSmjDkoe-1BrvKJ3tJzjWo-6y63lfvVU9R',
        name: 'Twister The Dog',
        symbol: 'TWIDO',
        image: 'https://assets.dedust.io/images/twido.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCH44N73BXEhT8063KAK_27oComvJnmAaebso-dZoyAy6g_',
        name: 'MMM2049',
        symbol: 'MMM',
        image: 'https://assets.dedust.io/images/mmm.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQBB7RWO0qzo6JhikXLjmKJc81IS4JR0cyc5bPAL_h0GGmxW',
        name: 'Portal Network Token',
        symbol: 'POE',
        image: 'https://assets.dedust.io/images/poe.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQARgJ-aCPIyOr4WDckDVcdXQHRPAjTjBNatopiRS9FnUEmn',
        name: 'MOLOKO',
        symbol: 'MOLOKO',
        image: 'https://assets.dedust.io/images/moloko.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQC8XkUEWb6bzbzE9eVaASoKUCyYA_CUQALGE15jWInEqla6',
        name: 'PONKE TON',
        symbol: 'PONKE',
        image: 'https://assets.dedust.io/images/ponke.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCl0S4xvoeGeFGijTzicSA8j6GiiugmJW5zxQbZTUntre-1',
        name: 'swap.coffee',
        symbol: 'CES',
        image: 'https://assets.dedust.io/images/ces.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDE2iOVhvteBA8bCxywcmCOPVxJGltPhft8RYDTXiv4lmvM',
        name: 'Engage ADS on Ton Open Network',
        symbol: 'EAT',
        image: 'https://assets.dedust.io/images/eat.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCXSMNX3OB5jPgOJkEzjYhm7FOBfkA3cg7paBqTYwzXrjIi',
        name: 'Cubigator',
        symbol: 'CUB',
        image: 'https://assets.dedust.io/images/cub.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQC2wH1I9MVQCWvVCNfA85N_TF3tSI50DEE597QNdO66rclf',
        name: 'BROKIE ON TON',
        symbol: 'BROTON',
        image: 'https://assets.dedust.io/images/broton.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAgotSkX06MIW-A0ni5yKqeNlwc3nASnbO1dwGo-kwpg2Zg',
        name: 'PizzaTon Token',
        symbol: 'PTJ',
        image: 'https://assets.dedust.io/images/pizzaton.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDqvdTKpRROsk1_iI-8Fxx1u7W54jRumGzgn0jQoJSY1bqX',
        name: 'Riki',
        symbol: 'RC',
        image: 'https://assets.dedust.io/images/riki.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQC7vuKEYLdC72YhUWt3AUVA-Oi66Q1DxTHXH7r6pXaV50j7',
        name: 'Baby Yoda',
        symbol: 'YODA',
        image: 'https://assets.dedust.io/images/yoda.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDqZlrARv4jPJpwzbYPNiOtD_CouWxeAGbp7awAzoezQImY',
        name: 'Dimethyltryptamine',
        symbol: 'DMT',
        image: 'https://assets.dedust.io/images/dmt.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD6W0raB1aGCr86pWd7-oWpA3QW2VXCJ9smlYcChkIhflt2',
        name: 'CAVIAR COIN',
        symbol: 'CAVI',
        image: 'https://assets.dedust.io/images/cavi.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCFVNlRb-NHHDQfv3Q9xvDXBLJlay855_xREsq5ZDX6KN-w',
        name: 'MyTonWallet Coin',
        symbol: 'MY',
        image: 'https://assets.dedust.io/images/my.webp',
        decimals: 9,
        aliased: true,
    },
    {
        type: 'jetton',
        address: 'EQDmj_i7VMXstzF9dTgQMyPKyvQIynYD0KJ7pI8v1LU400Rh',
        name: 'Wonnie',
        symbol: 'WON',
        image: 'https://assets.dedust.io/images/wonnie.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQByVysfErmFFWpaCXIHU68SF0v6O0g59KWhrqxeBPDyjEQ_',
        name: 'GOLD',
        symbol: 'AGLD',
        image: 'https://assets.dedust.io/images/agld.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAik8dthQ2NheRlkvnCRJPuDcmGmitTeZEL9dNkKfQyffjo',
        name: 'BEN',
        symbol: 'BEN',
        image: 'https://assets.dedust.io/images/ben.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB22u_EPF5DyqtZRhjJ2YiZliN-w5ZCq6F_PY6Ia6bvi3Et',
        name: 'Pavel Durov',
        symbol: 'DUROV',
        image: 'https://assets.dedust.io/images/durov.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDUWu9M_5NR812aj5rI3FDBgnVbLyycvj-Fb_u0F__CLOSE',
        name: 'Closecoin',
        symbol: 'CLOSE',
        image: 'https://assets.dedust.io/images/close.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD7rlGEfvNUXYbEwT-Ll7SUD7LuGkubUeU-TQXsShMwXY0H',
        name: 'Saintcoin',
        symbol: 'SAINT',
        image: 'https://assets.dedust.io/images/saint.webp',
        decimals: 7,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDRlQ8en7A2zsTuF7SdDOxMlZ_wFw0E7Eow3u9c4pSoe4Tg',
        name: 'TGram',
        symbol: 'TGRAM',
        image: 'https://assets.dedust.io/images/tgram.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDhSXj-di6Wo6__Pqd51dHZHel0MQeaegmhCWm-tkwwtem8',
        name: 'Microdiving',
        symbol: 'MIC',
        image: 'https://assets.dedust.io/images/mic.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCCSdlx31KvjbsW-rHdgsLSLUdrj64aZI5DTBBHMeZIVulP',
        name: 'DONALDTRUMP',
        symbol: 'DTRUMP',
        image: 'https://assets.dedust.io/images/dtrump.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQD9zg_jMBEjQCwKln1xOO4iaf6F4r4R6YgXWPqIeWKqrTqj',
        name: 'Nuka Cola',
        symbol: 'NC',
        image: 'https://assets.dedust.io/images/nukacola.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDXyN5QEtQJOGxYOpGmleB7uazJrl-Zzim2e77Su1nKYjJ-',
        name: 'MOON',
        symbol: 'MOON',
        image: 'https://assets.dedust.io/images/moon.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQA4-dwC_PyhZZkgoCDtMvaIIGPUXuOZFsH6q4N9xbaWFXvD',
        name: 'MONKE',
        symbol: 'MK',
        image: 'https://assets.dedust.io/images/mk.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAQElB3trMwj0wCnVVYYFnJrbpwCO_NXDaTuj9aYigLovXw',
        name: 'Wakeup DAO Token',
        symbol: 'WAKEUP',
        image: 'https://assets.dedust.io/images/wakeup.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAWy9ddqQJgwtCR-H4QsPOIcZsr55O-O6eI4sZj28dWzgLA',
        name: 'Ton Doge Coin',
        symbol: 'TonDoge',
        image: 'https://assets.dedust.io/images/tondoge.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCJLFpI0QR1QA_CYQ77Zm1_n85RDM4yLS46voZGRWbu9sbX',
        name: 'Dog or Flower',
        symbol: 'OR',
        image: 'https://assets.dedust.io/images/or.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQB8uhcKPm9IavIEzonGkPG85aIIXPonr5yPSesaXRnVU2JJ',
        name: 'GAS000',
        symbol: 'GAS000',
        image: 'https://assets.dedust.io/images/gas000.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQA2FHorTzvYpsM3t_6IqMuigpJZCB_-5H80CqbIIaULq272',
        name: 'CHORRY',
        symbol: 'CHORRY',
        image: 'https://assets.dedust.io/images/chorry.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQCm-KzJ6kacK9lhrnOaHR-W1KJGm-H415bEgsI04IVTDM57',
        name: 'PDF Miner Boost',
        symbol: 'PDFB',
        image: 'https://assets.dedust.io/images/pdfb.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQDxiBc5tH3rGL7xVthFz84SWFyFVQPGOmhHghrf1VA4LBTu',
        name: 'SLUT',
        symbol: 'SLUT',
        image: 'https://assets.dedust.io/images/slut.webp',
        decimals: 9,
        aliased: false,
    },
    {
        type: 'jetton',
        address: 'EQAQB8Ut4tnlOl54this4vZqkWTVISybPnx_XID9337WzVra',
        name: 'Save Ass Coin',
        symbol: 'SAC',
        image: 'https://assets.dedust.io/images/sac.webp',
        decimals: 9,
        aliased: false,
    },
];
