name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: andryaschuk/dermo:latest
                  build-args: |
                      MNEMONIC=${{ secrets.MNEMONIC }}
                      SUPABASE_PUBLIC_KEY=${{ secrets.SUPABASE_PUBLIC_KEY }}
                      SUPABASE_URL=${{ secrets.SUPABASE_URL }}
                      TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
                      TG_GROUP_ID=${{ secrets.TG_GROUP_ID }}
                      TONAPI_TOKEN=${{ secrets.TONAPI_TOKEN }}

    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push

        steps:
            - name: Connect to SSH and setup new docker container
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull andryaschuk/dermo:latest
                      docker stop snipe || true
                      docker rm snipe || true
                      docker run -d --name snipe andryaschuk/dermo:latest
